back/Restaurante/Restaurante/ViewModels/RestauranteViewModel.cs
using Potatotech.GestaoRestaurante.Dominio.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Potatotech.GestaoRestaurante.Web.ViewModels
{
    public class RestauranteViewModel
    {

        public int qtdMesas { get; set; }
        public int qtdAmbientes { get; set; }
        public ICollection<Ambiente> listaAmbientes { get; set; }
        public Usuario gerente { get; set; }
        public Ambiente ambiente { get; set; }
        
    }
}

back/Restaurante/Restaurante/Controllers/RestauranteController.cs
using Potatotech.GestaoRestaurante.Dominio.Models;
using Potatotech.GestaoRestaurante.Persistencia.UnitsOfWork;
using Potatotech.GestaoRestaurante.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Potatotech.GestaoRestaurante.Web.Controllers
{
    [Authorize]
    public class RestauranteController : Controller
    {

        #region PRIVATE

        UnitOfWork _unit = new UnitOfWork();

        #endregion

        #region GET

        [HttpGet]
        public ActionResult Listar()
        {
            RestauranteViewModel viewRestaurante = new RestauranteViewModel()
            {
                listaAmbientes = _unit.AmbienteRepository.Listar()
            };
            return View(viewRestaurante);
        }

        #endregion

        #region POST

        [HttpPost]
        public ActionResult Cadastrar(RestauranteViewModel viewRestaurante)
        {
            Ambiente ambiente = new Ambiente()
            {
                Id = viewRestaurante.ambiente.Id,
                Nome = viewRestaurante.ambiente.Nome
            };
            _unit.AmbienteRepository.Cadastrar(ambiente);
            _unit.Salvar();
            return RedirectToAction("Listar");
        }

        //[HttpPost]
        public ActionResult Deletar(int idAmb)
        {
            _unit.AmbienteRepository.Remover(idAmb);
            _unit.Salvar();
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Editar(RestauranteViewModel viewRestaurante)
        {
            Ambiente ambiente = new Ambiente()
            {
                Id = viewRestaurante.ambiente.Id,
                Nome = viewRestaurante.ambiente.Nome
            };
            _unit.AmbienteRepository.Alterar(ambiente);
            _unit.Salvar();
            return RedirectToAction("Listar");
        }

        #endregion POST

    }
}

back/Restaurante/Restaurante/Views/Restaurante/Listar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RestauranteViewModel
@{
    ViewBag.Title = "Lista de ambientes";
}

<div class="x_panel">
    <div class="x_title">

        <div class="row">
            <div class="col-md-10">
                <h2>Lista de ambientes</h2>
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#Cadastrar">
                    + Ambiente
                </button>
            </div>
        </div>

    </div>
    <div class="x_content">
        <table class="table">
            <thead class="row">
                <tr>
                    <th class="col-md-1">Id</th>
                    <th class="col-md-9">Nome</th>
                    <th class="col-md-2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var a in Model.listaAmbientes)
                {
                    <tr>
                        <th>@a.Id</th>
                        <th>@a.Nome</th>
                        <td>
                            <button data-id="@a.Id" class="btn btn-primary edit" data-toggle="modal" data-target="#Editar">Editar</button>
                            <button onclick="idAmb.value = @a.Id " type="button" class="btn btn-danger" data-toggle="modal" data-target="#Deletar">Apagar</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.Partial("_cadastrar")
        @Html.Partial("_editar")
        @Html.Partial("_deletar")
    </div>
</div>

@section scripts{
    <script>
        $().ready(function () {
            $(".edit").click(function () {
                $.ajax({
                    url: "http://localhost:8014/api/Ambiente/" + $(this).data("id"),
                    method: "GET",
                    success: function (data) {
                        $("#cod").val(data.Id);
                        $("#nome").val(data.Nome);
                    }
                })
            })
        })
    </script>
}

back/Restaurante/Restaurante/Views/Restaurante/_cadastrar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RestauranteViewModel

<div class="modal fade" id="Cadastrar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cadastrar ambiente</h4>
            </div>
            @using (Html.BeginForm("Cadastrar", "Restaurante"))
            {
                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(a => a.ambiente.Nome)
                        @Html.TextBoxFor(a => a.ambiente.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.ambiente.Nome)
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                </div>
            }
        </div>
    </div>
</div>

back/Restaurante/Restaurante/Views/Restaurante/_deletar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RestauranteViewModel

<div class="modal fade" id="Deletar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
            </div>
            <div class="modal-body">
                Deseja apagar?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Deletar", "Restaurante"))
                {
                    <input type="hidden" id="idAmb" name="idAmb" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-primary">Sim</button>
                }
            </div>
        </div>
    </div>
</div>

back/Restaurante/Restaurante/Views/Restaurante/_editar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RestauranteViewModel

<div class="modal fade" id="Editar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar ambiente</h4>
            </div>
            @using (Html.BeginForm("Editar", "Restaurante"))
            {
                <div class="modal-body">
                    <input type="hidden" id="ambienteId" name="ambienteId" />
                    <div class="form-group">
                        @Html.LabelFor(a => a.ambiente.Id)
                        @Html.TextBoxFor(a => a.ambiente.Id, new { @class = "form-control", @readonly = "readonly", id = "cod" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.ambiente.Nome)
                        @Html.TextBoxFor(a => a.ambiente.Nome, new { @class = "form-control", id = "nome" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-block">Editar ambiente</button>
                </div>
            }
        </div>
    </div>
</div>