back/Restaurante/Restaurante/Models/Mesa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potatotech.GestaoRestaurante.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesa()
        {
            this.Conta = new HashSet<Conta>();
        }
    
        public int Id { get; set; }
        public int Capacidade { get; set; }
        public bool Ocupada { get; set; }
        public int AmbienteId { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conta> Conta { get; set; }
    }
}

back/Restaurante/Restaurante/ViewModels/MesaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Potatotech.GestaoRestaurante.Dominio.Models;
using System.ComponentModel.DataAnnotations;

namespace Potatotech.GestaoRestaurante.Web.ViewModels
{
    public class MesaViewModel
    {

        public int Id { get; set; }
        public int Capacidade { get; set; }
        public bool Ocupada { get; set; }
        public int AmbienteId { get; set; }
        
        public virtual Ambiente Ambiente { get; set; }
        public virtual ICollection<Conta> Conta { get; set; }

        public SelectList AmbienteSelectList { get; set; }

    }
}

back/Restaurante/Restaurante/Controllers/MesaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using AutoMapper;
using Potatotech.GestaoRestaurante.Dominio.Models;
using Potatotech.GestaoRestaurante.Persistencia.UnitsOfWork;
using Potatotech.GestaoRestaurante.Web.ViewModels;

namespace Potatotech.GestaoRestaurante.Web.Controllers
{
   
    [Authorize]
    public class MesaController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();
        // GET: Mesa

        #region GET
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View();
        }

        [HttpGet]
        public ActionResult TabelaMesa(int pagina)
        {
            if (pagina < 1)
            {
                return HttpNotFound("Página inválida");
            }
            pagina -= 1;
           
            int TAMANHO_PAGINA = 5;
            var listaraw =
                _unit.MesaRepository.Listar()
                    .ToList()
                    .Skip(pagina*TAMANHO_PAGINA)
                    .Take(TAMANHO_PAGINA);

            return PartialView("_tabela", Mapper.Map<List<MesaViewModel>>(listaraw));
        }

        [HttpGet]
        public ActionResult FormMesa()
        {
            var vm = new MesaViewModel()
            {
                AmbienteSelectList = SelectAmbiente()
            };

            return PartialView("_adicionar", vm);
        }
        #endregion

        #region POST

        [HttpPost]
        public ActionResult Adicionar(MesaViewModel mesaViewModel)
        {
            if (ModelState.IsValid)
            {
                _unit.MesaRepository.Cadastrar(Mapper.Map<Mesa>(mesaViewModel));
                _unit.Salvar();
            }
            return Redirect(Request.UrlReferrer.AbsolutePath);

        }

        #endregion

        #region SELECT
        private SelectList SelectAmbiente()
        {
            var ambientes = _unit.AmbienteRepository.Listar();
            return new SelectList(ambientes, "Id", "Nome");
        }
        #endregion


    }

}

back/Restaurante/Restaurante/Views/Mesa/Listar.cshtml
<div class="x_panel">
    <div class="x_title">
        <div class="row">
            <div class="col-xs-10">
                <h2>Mesas</h2>
            </div>
            <div class="col-xs-2">
                <button type="button" class="btn btn-success" onclick="abrirModal()">
                    Adicionar
                </button>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    
    <div class="x_content">
        <div id="tabela-container">
            
        </div>
        
        <ul class="pagination">

            <li onclick="paginaAnterior()"><a><</a></li>
            <li class="active"><a id="pagina-atual">/1</a></li>
            <li onclick="proximaPagina()"><a>></a></li>

        </ul>
    </div>
    <div class="modal fade" tabindex="-1" id="modal-form" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" id="modal-container">

            </div>
        </div>
    </div>
</div>



@section Scripts {
<script>
    $(function () {
        atualizarTabela(1);
    });

    function atualizarTabela(pagina) {
        toastr.info("Carregando");
        $.get('/Mesa/TabelaMesa?pagina=' + pagina)
            .done(function (data) {
                $('#tabela-container').html(data);
                $('#pagina-atual').html(pagina);
                toastr.clear();
            })
            .fail(function (error) {
                console.log(error);
                toastr.clear();
                toastr.warning("Página não encontrada");
            });

    }

    function proximaPagina() {

        atualizarTabela(parseInt($('#pagina-atual').html()) + 1);

    }

    function paginaAnterior() {
        atualizarTabela($('#pagina-atual').html() - 1);
    }
    
    function abrirModal() {
        toastr.info("Carregando");
        $.get('/Mesa/FormMesa')
            .done(function (data) {
                console.log(data);
                $('#modal-container').html(data);
                $('#modal-form').modal('show');
                toastr.clear();
            })
            .error(function() {
                toastr.clear();
                toastr.error("Erro");
            });
    }
</script>
}

back/Restaurante/Restaurante/Views/Mesa/_adicionar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.MesaViewModel
    
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <h4 class="modal-title" id="myModalLabel2">Adicionar Novo</h4>
</div>
@using (Html.BeginForm("Adicionar", "Mesa"))
{
    <div class="modal-body">

        <div class="modal-body">
            <div class="form-group">
                @Html.LabelFor(p => p.Id)
                @Html.TextBoxFor(p => p.Id, new {@class = "form-control"})
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Ambiente)
                @Html.DropDownListFor(p => p.AmbienteId, Model.AmbienteSelectList, new {@class = "form-control"})
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Capacidade)
                @Html.TextBoxFor(p => p.Capacidade, new {@class = "form-control"})
            </div>
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <input type="submit" class="btn btn-success" name="Adicionar"/>
    </div>
}

back/Restaurante/Restaurante/Views/Mesa/_tabela.cshtml
@model List<Potatotech.GestaoRestaurante.Web.ViewModels.MesaViewModel>
    
<table class="table">
    <thead class="row">
    <tr>
        <th class="col-md-2">Número</th>
        <th class="col-md-2">Capacidade</th>
        <th class="col-md-2">Status</th>
        <th class="col-md-2">Ambiente</th>
        <th class="col-md-2">Ações</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var m in Model)
    {
        <tr>
            <td>@m.Id</td>
            <td>@m.Capacidade</td>
            <td>@(m.Ocupada ? "Ocupada" : "Livre")</td>
            <td>@m.Ambiente.Nome</td>
        </tr>
    }
    </tbody>
</table>