back/Restaurante/Restaurante/ViewModels/RecepcaoViewModel.cs
using Potatotech.GestaoRestaurante.Dominio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Potatotech.GestaoRestaurante.Web.ViewModels
{
    public class RecepcaoViewModel
    {

        public ICollection<Mesa> Mesas { get; set; }

        public int MesaId { get; set; }

        public virtual Mesa Mesa { get; set; }
        public bool Ocupada { get; set; }


    }
}

back/Restaurante/Restaurante/Controllers/RecepcaoController.cs
using Potatotech.GestaoRestaurante.Dominio.Models;
using Potatotech.GestaoRestaurante.Persistencia.UnitsOfWork;
using Potatotech.GestaoRestaurante.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Potatotech.GestaoRestaurante.Web.Controllers
{
    [Authorize]
    public class RecepcaoController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Listar()
        {
            var lista = _unit.MesaRepository.Listar();
            

            var viewModel = new RecepcaoViewModel()
            {
                Mesas = lista,
                
            };

            return View(viewModel);
        }

        public ActionResult AlterarStatus(int id)
        {
            var viewModel = new RecepcaoViewModel();
            var mesa = _unit.MesaRepository.BuscarPorId(id);

            if (mesa.Ocupada == false)
            {
                viewModel = new RecepcaoViewModel()
                {
                    
                    Ocupada = true
                };
                mesa.Ocupada = true;
            }
            else
            {
                viewModel = new RecepcaoViewModel()
                {
                    Ocupada = false
                };

                mesa.Ocupada = false;
            }

            _unit.MesaRepository.Alterar(mesa);
            _unit.Salvar();

            return RedirectToAction("Listar", viewModel);
        }
    }
}

back/Restaurante/Restaurante/Views/Recepcao/Listar.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RecepcaoViewModel
@{
    ViewBag.Title = "Listar";
}



<div class="x_panel">
    <div class="x_tittle">
        <h3>Lista de Mesas</h3>
        <hr />
    </div>
    <div class="x_content">
        <table class="table table-hover">
            <thead class="row">
                <tr>
                    <th class="col-md-2">Número</th>
                    <th class="col-md-2">Capacidade</th>
                    <th class="col-md-2">Status</th>
                    <th class="col-md-2">Ambiente</th>
                    <th class="col-md-2">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model.Mesas)
                {
                    <tr>
                        <td>@m.Id</td>
                        <td>@m.Capacidade</td>
                        <td>@(m.Ocupada ? "Ocupada" : "Livre")</td>
                        <td>@m.Ambiente.Nome</td>
                        <td>@Html.ActionLink("Alterar Status", "AlterarStatus", new { id = @m.Id }, new { @class = "btn btn-primary" })</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

back/Restaurante/Restaurante/Views/Recepcao/_changeStatus.cshtml
@model Potatotech.GestaoRestaurante.Web.ViewModels.RecepcaoViewModel

<div class="modal fade" id="Alterar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Alterar Status</h4>
            </div>
            @using(Html.BeginForm("AlterarStatus", "Recepcao")) { 
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(p => p.Id)
                    @Html.TextBoxFor(p => p.Id, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Ambiente)
                    @Html.DropDownListFor(p => p.AmbienteId, Model.AmbienteSelectList, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Capacidade)
                    @Html.TextBoxFor(p => p.Capacidade, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Ocupada)
                    @Html.CheckBoxFor(p => p.Ocupada)
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
            }
        </div>
    </div>
</div>

back/Restaurante/Restaurante/Views/Recepcao/_tabela.cshtml
@model List<Potatotech.GestaoRestaurante.Dominio.Models.Mesa>